// SPDX-License-Identifier: Apache-2.0
#ifndef ZXINGQTQMLWRITER_H
#define ZXINGQTQMLWRITER_H

#include <QObject>
#include <QQuickPaintedItem>
#include <QQmlEngine>
#include <QImage>

//Example of class which can draw QR code in QML based on
//QImage generated by ZXing
class ZXingQtQmlWriter : public QQuickPaintedItem
{
	Q_OBJECT
	QML_ELEMENT

public:
	explicit ZXingQtQmlWriter(QQuickPaintedItem* parent = nullptr);

	//Method based on code from ZXingQtWriter.cpp created by Axel Waggershauser.
	//Method uses ZXing::BarcodeFormat::QRCode format - different formats can be
	//supported by passing the format as argument or changing format inside method
	//implementation
	Q_INVOKABLE void generateBarcode(const QString &text);

	// QQuickPaintedItem interface
	void paint(QPainter *painter);

private:
	QImage m_qrCode;
};


#endif // ZXINGQTQMLWRITER_H
