// Copyright 2026 Axel Waggershauser
// SPDX-License-Identifier: Apache-2.0

extension BarcodeFormat {
	public static let invalid         = BarcodeFormat(rawValue: 0xFFFF)
	public static let none            = BarcodeFormat(rawValue: 0x0000)
	public static let all             = BarcodeFormat(rawValue: 0x2A2A)
	public static let allReadable     = BarcodeFormat(rawValue: 0x722A)
	public static let allCreatable    = BarcodeFormat(rawValue: 0x772A)
	public static let allLinear       = BarcodeFormat(rawValue: 0x6C2A)
	public static let allMatrix       = BarcodeFormat(rawValue: 0x6D2A)
	public static let allGS1          = BarcodeFormat(rawValue: 0x472A)
	public static let allRetail       = BarcodeFormat(rawValue: 0x522A)
	public static let allIndustrial   = BarcodeFormat(rawValue: 0x492A)
	public static let codabar         = BarcodeFormat(rawValue: 0x2046)
	public static let code39          = BarcodeFormat(rawValue: 0x2041)
	public static let code39Std       = BarcodeFormat(rawValue: 0x7341)
	public static let code39Ext       = BarcodeFormat(rawValue: 0x6541)
	public static let code32          = BarcodeFormat(rawValue: 0x3241)
	public static let pzn             = BarcodeFormat(rawValue: 0x7041)
	public static let code93          = BarcodeFormat(rawValue: 0x2047)
	public static let code128         = BarcodeFormat(rawValue: 0x2043)
	public static let itf             = BarcodeFormat(rawValue: 0x2049)
	public static let itf14           = BarcodeFormat(rawValue: 0x3449)
	public static let dataBar         = BarcodeFormat(rawValue: 0x2065)
	public static let dataBarOmni     = BarcodeFormat(rawValue: 0x6F65)
	public static let dataBarStk      = BarcodeFormat(rawValue: 0x7365)
	public static let dataBarStkOmni  = BarcodeFormat(rawValue: 0x4F65)
	public static let dataBarLtd      = BarcodeFormat(rawValue: 0x6C65)
	public static let dataBarExp      = BarcodeFormat(rawValue: 0x6565)
	public static let dataBarExpStk   = BarcodeFormat(rawValue: 0x4565)
	public static let eanUPC          = BarcodeFormat(rawValue: 0x2045)
	public static let ean13           = BarcodeFormat(rawValue: 0x3145)
	public static let ean8            = BarcodeFormat(rawValue: 0x3845)
	public static let ean5            = BarcodeFormat(rawValue: 0x3545)
	public static let ean2            = BarcodeFormat(rawValue: 0x3245)
	public static let isbn            = BarcodeFormat(rawValue: 0x6945)
	public static let upcA            = BarcodeFormat(rawValue: 0x6145)
	public static let upcE            = BarcodeFormat(rawValue: 0x6545)
	public static let otherBarcode    = BarcodeFormat(rawValue: 0x2058)
	public static let dxFilmEdge      = BarcodeFormat(rawValue: 0x7858)
	public static let pdf417          = BarcodeFormat(rawValue: 0x204C)
	public static let compactPDF417   = BarcodeFormat(rawValue: 0x634C)
	public static let microPDF417     = BarcodeFormat(rawValue: 0x6D4C)
	public static let aztec           = BarcodeFormat(rawValue: 0x207A)
	public static let aztecCode       = BarcodeFormat(rawValue: 0x637A)
	public static let aztecRune       = BarcodeFormat(rawValue: 0x727A)
	public static let qrCode          = BarcodeFormat(rawValue: 0x2051)
	public static let qrCodeModel1    = BarcodeFormat(rawValue: 0x3151)
	public static let qrCodeModel2    = BarcodeFormat(rawValue: 0x3251)
	public static let microQRCode     = BarcodeFormat(rawValue: 0x6D51)
	public static let rmqrCode        = BarcodeFormat(rawValue: 0x7251)
	public static let dataMatrix      = BarcodeFormat(rawValue: 0x2064)
	public static let maxiCode        = BarcodeFormat(rawValue: 0x2055)
}
