/*
 * This header is only used to satisfy the include dependency chain when compiling
 * the public C headers from the zxing-cpp source tree via cgo.
 *
 * In normal installations, the real Version.h is generated by CMake from
 * core/Version.h.in and installed alongside the other public headers.
 */

#pragma once

// The C headers included by the Go wrapper do not require these values for
// correctness (they are mainly used for feature flags / build-time reporting).
// Provide conservative defaults so compilation works without running CMake.

#ifndef ZXING_ENABLE_1D
#define ZXING_ENABLE_1D 1
#endif

#ifndef ZXING_ENABLE_AZTEC
#define ZXING_ENABLE_AZTEC 1
#endif

#ifndef ZXING_ENABLE_DATAMATRIX
#define ZXING_ENABLE_DATAMATRIX 1
#endif

#ifndef ZXING_ENABLE_MAXICODE
#define ZXING_ENABLE_MAXICODE 1
#endif

#ifndef ZXING_ENABLE_PDF417
#define ZXING_ENABLE_PDF417 1
#endif

#ifndef ZXING_ENABLE_QRCODE
#define ZXING_ENABLE_QRCODE 1
#endif
